In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt




In [10]:
vector=np.array([1,2,3])

print(vector)

print(f'Dimensión: {vector.shape}')


print(f'Cantidad de dimensiones: {vector.shape}') 
print(f'Cantidad de dimensiones: {vector.ndim}') 
print(f'Cantidad total de elementos: {vector.size}') 
print(f'Tipo de dato: {vector.dtype}') 
print(f'Tamaño en bytes de cada elemento: {vector.itemsize}') 
print(f'Datos de una matriz en objeto buffer: {vector.data}') 

vector2=np.array(["Hola","Adiós"])

print(f'Tipo de dato: {vector2.dtype}')

[1 2 3]
Dimensión: (3,)
Cantidad de dimensiones: (3,)
Cantidad de dimensiones: 1
Cantidad total de elementos: 3
Tipo de dato: int64
Tamaño en bytes de cada elemento: 8
Datos de una matriz en objeto buffer: <memory at 0x0000023D3A3B4B80>
Tipo de dato: <U5


In [12]:
vector1=np.array([2,3,4])
vector2=np.array([4,5,7])

resultado=np.dot(vector1,vector2)

print(resultado)

51


In [ ]:
matriz=np.array(([1,2,4,5], [3,4,6,8] , [2,5,7,1], [2,4,6,0]))


print(matriz)


print(matriz.shape)

matriz_reshape=matriz.reshape(2,8)

print(matriz_reshape)

matriz_transpose=matriz.transpose()

print(matriz_transpose)

[[1 2 4 5]
 [3 4 6 8]
 [2 5 7 1]
 [2 4 6 0]]
(4, 4)
[[1 2 4 5 3 4 6 8]
 [2 5 7 1 2 4 6 0]]
[[1 3 2 2]
 [2 4 5 4]
 [4 6 7 6]
 [5 8 1 0]]


Ejercicios Numpy


In [4]:
matriz=np.ones((3,3), dtype=bool)


print(matriz)

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

for i in arr:
    if i%2!=0:
       arr[i]=-1
       
       
print(arr)

arr2 = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

reshape=arr2.reshape(2,5)

print(reshape)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[[0 1 2 3 4]
 [5 6 7 8 9]]
